### ISSUE TITLE
custom menu items and local static pages

### ISSUE THREAD

**Issue by nikolau** [moodleuulm/moodle-local_staticpage#21] opened 2017-02-06 16:25 UTC
Hi Alexander

Thanks for plugin, I'm started to work on moodle project and have a problem with "custom menu items" , installed you plugin v3.1-r2 on version 3.1.4 + , with "tikli" theme

Plugin works , I'm follow read me and everything seems to work. Bug I have "custom menu items" are not listed on any static page I'm open, only two links are listed and generated on correct position "login" and "create new account" . However if I log in and reopen static page , "custom menu items" are there in correct position, visible and work as they should be for any website visitor.

So user that is not logged in can't see my "custom menu items" links.

Here is the [link](http://euqinorev.com/local/staticpage/view.php?page=[whoweare]) , if you go back to homepage, custom menu items are on position. Here are [screenshots](http://euqinorev.com/screen.png)

Do you have some idea why that happening, or where to look to fix it ? Or this question is more correct for theme autor ?

Thanks,
Nikola

**Comment by abias** [comment] 2017-02-07 06:52
Hi Nikola,

thanks for the screenshots. Now I fully understand your problem.

However, I was not able to reproduce the problem on my systems. I have custom menu items on static pages even if I am not logged in and I don't see a reason in my plugin why it should be different.

Your hint about the Tikli theme is important. As this is a non-free theme, I can't check if it behaves different than the Moodle core themes.

Could you please
* Check if the problem is the same on Moodle core themes like theme_clean or theme_more?
* Take the latest release v3.2-r5 (and remove the line https://github.com/moodleuulm/moodle-local_staticpage/blob/master/version.php#L29 to run it on Moodle 3.1) to see if the problem persists in the latest release.

PS: You should remove the brackets from the static page URL so that it says http://euqinorev.com/local/staticpage/view.php?page=whoweare - because the brackets get removed anyway when the page is delivered.

**Comment by abias** [comment] 2017-02-07 12:16
Hi Nikola,

it's good news that it works correctly with theme_clean. Thus, I dare to close this ticket.

> Do you have idea why this theme would show "login" and "create new account" links, and for some reason skip "custom menu items" for non logged users, while rendering static local page ? I believe there is a few locations where i can look and compare to check what is different.

As far as I know, Tikli is a paid theme, so why not create a support request with the vendor of the theme?

It difficult to point you to a location where you could find a problem in your theme, but a good start would be to grep for custommenu or custom_menu in the code of the theme to find locations where the theme is doing something with the custom menu.

Good luck!

Thanks,
Alex

**Closed by abias** 2017-02-07 12:16 UTC

**Comment by nikolau** [comment] 2017-02-08 03:34
if someone have same problem with theme I'm use, there was missing line in header.php

` <div class="nav-collapse collapse">
      <?php echo $OUTPUT->custom_menu();?>
    </div>`

**Comment by abias** [comment] 2017-02-08 06:25
Hi Nikola,

I am happy to hear that it finally worked for you.

Thanks,
Alex
