### ISSUE TITLE
Use of Javascript on page

### ISSUE THREAD

**Issue by richardschwarz** [moodleuulm/moodle-local_staticpage#63] opened 2022-01-03 07:57 UTC
Hi!

I'm trying to do up an easy page for my teaching staff to delete their course, after being reminded to back it up.
The idea is that they would access it via a link in a drop-down in the Custom Menu (like "Delete this course") which then goes to this page. The page can detect the course page it came from (using javascript in the head section on load), but I can't then put that value into buttons for backing up or for deleting...

Head section:
<script>
var oldURL = document.referrer;
alert(oldURL);
const lastSegment = oldURL.split("=").pop();

alert(lastSegment);
</script>

Then at base of page:
<script>document.getElementById('btnBackup').innerHTML = "<a class='btn btn-lg btn-success' href='https://moodle.fcc.qld.edu.au/backup/backup.php?id=${lastSegment}' role='button'>Backup this course!</a>";</script>

NOTE: I tried to have it in the head section as well, but that obviously doesn't work... 

It just creates the link as: https://moodle.fcc.qld.edu.au/backup/backup.php?id=${lastSegment}, which is interesting as it's using the JS at the base of the page to put that in, but not the variable?

Picture of Code:
![code picture](https://user-images.githubusercontent.com/145715/147909204-ae3e0fa7-37d2-463d-921a-254a8e2cdaa9.jpg)

Picture of URL:
![moodle picture](https://user-images.githubusercontent.com/145715/147909232-29c9efac-656a-4343-84b1-6d7e7e0f01ae.jpg)

Any ideas?

**Comment by abias** [comment] 2022-01-05 21:33
Hi @richardschwarz ,

I am impressed by what you try to achieve with this plugin, but this issue feels like a duplicate of #40 which can be summarized as "there is no reliable support for JavaScript code in local_staticpage pages' content and there is no real plan to add it".

There is another plugin on https://moodle.org/plugins/local_pages which does similar things than this one but which I have never tried. Maybe you want to have a look if it supports JavaScript like you expect it.

Cheers,
Alex

**Closed by abias** 2022-01-05 21:33 UTC
