### ISSUE TITLE
Html code when using static pages

### ISSUE THREAD

**Issue by cpuntotax** [moodleuulm/moodle-local_staticpage#16] opened 2016-11-02 20:57 UTC
We have installed the plugin static page v3.1-r2 with moodle 3.1.1.
We have a problem and a question

The problem:
Using static page with an html responsive webpage with a CSS Inline, after the publication of the page, this line of code appears on the top of the page content:

YPE html PUBLIC "- //W3C//DTD HTML 4.0 Transitional//ENs" "http://www.w3.org/TR/REC-html40/loose.dtd" >

Example page: http://www.formanager.net/learning/local/staticpage/view.php?page=chisiamo4

The source code pf the page is downloadable at https://www.dropbox.com/s/lfmmnaac7bz31ut/chisiamo4_ok.txt?dl=0 

How can we fix this issue?

The question:
Is it possible to integrate with your plugin an html webpage that references files in external folder (for example: Javascript, css, images, fonts, etc)?
Here is an example of this solution: 

http://www.formanager.net/learning/local/staticpage/view.php?page=aiuto

We tried to upload to folder in the moodle root on the server referencing The external files inside the code of the page html. Applying this solution moodle loses its layout.
Does it exist a solution for integrating a page html with these characteristics? (no iframe).

Thanks in advance.

Best regards.

**Comment by abias** [comment] 2016-11-03 22:48
Hi cpuntotax,

concerning the strange string saying "YPE html PUBLIC ...":
If you remove the 
`bgcolor="#222222" width="100%" style="margin: 0;" `
attributes from the body tag, this string disappears. Without further investigation, I have no idea why this string appears, but I want to let you know that local_staticpage is not built to process any arbitrary HTML file.

Concerning the referenced files:
You can't upload referenced files in local_staticpage, they simply won't be processed. You are free to send us a pull request with this functionality :)
But you should be able to host the files somewhere else (for example, like you did, in the moodle root) - you just should reference these files with absolute URLs in the HTML code. Did you try that?

Thanks,
Alex

**Comment by abias** [comment] 2016-12-22 14:08
Hi cpuntotax,

as there was no answer from you anymore, I expect that your needs are fulfilled and I can close this ticket.

Thanks,
Alex

**Closed by abias** 2016-12-22 14:08 UTC

**Comment by actXc** [comment] 2017-05-01 19:41
Dear Alex,
thank you for sharing the plugin with the public.

I had the same #25 issue.
The reason was a non-standard meta-tag from a html doc created with M$-Word:
`<meta http-equiv=Content-Type content="text/html; charset=unicode">`
after changing **unicode** to **UTF-8** like in 
`<meta http-equiv=Content-Type content="text/html; charset=UTF-8">`
the symptom disappeared.

**Comment by abias** [comment] 2017-05-02 05:26
Hi Guido,

thanks for adding this detail, I hope it may help others who encounter this problem in the future.
In the plugin, we won't do anything about this problem as processing Word-HTML-files is clearly out of its scope.

Thanks,
Alex

**Comment by nise** [comment] 2020-09-20 19:56
Not allowing <meta> seems to be a bug that should be fixed since many people experienced similar problems.

**Comment by nise** [comment] 2020-09-20 20:07
As soon as I am adding 
`<meta charset="utf-8"/>` to the header and the attribute `lang="de"`to the body-tag I get the following error:

"YPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">"

Without adding the mentioned tags, German language (and maybe also French etc.) will not be rendered properly.

This ticket should be reoped and considered as a bug.

**Comment by abias** [comment] 2020-11-25 09:30
Hi @nise ,

thanks for adding your additional thoughts to this issue.

> Without adding the mentioned tags, German language (and maybe also French etc.) will not be rendered properly.

When this plugin was written many years ago, the goal was to clean the given HTML file as much as possible and only use and output the significant parts. However, this design decision should not lead to cases that a well-crafted HTML file is rendered improperly.

Would you mind to create a new issue with detailled steps to reproduce and an example HTML file which show that german language is not rendered properly?

Thanks,
Alex
