### ISSUE TITLE
First H1 heading duplicated, H2 heading not rendered

### ISSUE THREAD

**Issue by nakohdo** [moodleuulm/moodle-local_staticpage#52] opened 2021-04-21 10:21 UTC
When uploading the following sample HTML page, the first H1 heading is duplicated and the H2 heading is not rendered at all.

```
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title>Static Pages (title)</title>
	</head>
	<body>
		<h1>First H1 heading</h1>
		<div>[Your content goes here]</div>
		<p>For details see the  
			<a href="https://github.com/moodleuulm/moodle-local_staticpage/blob/master/README.md">plugin documentation</a>.
		</p>
		
		<h1>Heading 1</h1>
		<p>H1</p>
		<h2>Heading 2</h2>
		<p>H2</p>
		<h3>Heading 3</h3>
		<p>H3</p>
		<h4>Heading 4</h4>
		<p>H4</p>
		<h5>Heading 5</h5>
		<p>H5</p>
		<h6>Heading 6</h6>
		<p>H6</p>
	</body>
</html>
```

Moodle 3.10.3
Static Pages v3.10-r1

<img alt="headings_errors" src="https://user-images.githubusercontent.com/851953/115538665-6a7b5e80-a29c-11eb-92e1-c062c178d83d.png" width="200" />

**Comment by christianwolters** [comment] 2021-08-17 21:19
Hi @nakohdo,

I've just tested your HTML markup and I can't reproduce the omission of the level 2 heading, my test machine renders all headings as described in the file.

Regarding your the duplication of H1 heading: please check and play around with the static page settings in the are "Data source of document title". If you have set "documentheadingsource" to "First H1 Tag in HTML code (..." your screenshot shows the expected behavior: the H1 heading is not only shown in the document itself but also as the heading of the moodle page.

Best regards
Christian

**Comment by abias** [comment] 2021-12-08 20:47
As there wasn't any additional feedback, I will close this issue now.

Cheers,
Alex

**Closed by abias** 2021-12-08 20:47 UTC
