### ISSUE TITLE
Duplicate block

### ISSUE THREAD

**Issue by dolivervl** [moodleuulm/moodle-local_staticpage#58] opened 2021-08-30 17:48 UTC
I created two pages, names Contact.html and Teacher.html. When i added any block content to contact or Teacher, the same block appear to contact ou teacher.

Moodle  version 3.11.12
Theme Edumy version 2.6.0

**Comment by abias** [comment] 2021-12-08 20:47
I think this issue is a duplicate of #50 and should be discussed there.

Cheers,
Alex

**Closed by abias** 2021-12-08 20:47 UTC
